springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.displayOperationId=true
springdoc.swagger-ui.showCommonExtensions=true

springdoc.swagger-ui.syntaxHighlight.theme=obsidian